## Get docker-compose image from https://hub.docker.com/r/tmaier/docker-compose
services:
  - docker:dind

stages:
  - test
  - image_build
  - deploy_live

variables:
  # use the overlay storage driver
  # https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#using-the-overlayfs-driver
  DOCKER_DRIVER: overlay
  SERVER_CACHE_IMAGE: registry.gitlab.com/hovi-team-development/hovi-backend/server
  DATABASE_CACHE_IMAGE: registry.gitlab.com/hovi-team-development/hovi-backend/database

test:
  stage: test
  image: thuongnn1997/docker:stable
  only:
    - master
    - production
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - cd ./gitlab-ci
    - docker pull $DATABASE_CACHE_IMAGE:latest || true
    - docker pull $SERVER_CACHE_IMAGE:latest || true
    - docker-compose up --build --abort-on-container-exit
  after_script:
    - docker push $DATABASE_CACHE_IMAGE:latest
    - docker push $SERVER_CACHE_IMAGE:latest
  artifacts:
    name: "test-reports-$CI_PIPELINE_ID-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - ./hovi-server/coverage
