apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hovi-server
  name: hovi-server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: hovi-server
      tier: server
  template:
    metadata:
      labels:
        run: hovi-server
        tier: server
    spec:
      containers:
        - name: hovi-server
          image: registry.gitlab.com/hovi-team-development/hovi-backend/server:prod
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: HoviDB
            - name: MYSQL_USER
              value: hovi_user
            - name: MYSQL_PASSWORD
              value: hovi_password
            - name: MYSQL_HOST
              value: mysql.default.svc.cluster.local
          imagePullPolicy: Always
          args:
            - npm
            - run
            - start
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: gitlab-key
---
apiVersion: v1
kind: Service
metadata:
  name: hovi-server-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: hovi-server
  type: NodePort
