version: '3.7'

services:
  server-test:
    build:
      context: ../hovi-server
      cache_from:
        - registry.gitlab.com/hovi-team-development/hovi-backend/server:latest
    image: registry.gitlab.com/hovi-team-development/hovi-backend/server:latest
    container_name: hovi-server-test
    command: npm run test
    volumes:
      - ../hovi-server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: gitlabCI
    networks:
      - back-tier-test
    depends_on:
      - mysql-test
  mysql-test:
    build:
      context: ../hovi-database
      cache_from:
        - registry.gitlab.com/hovi-team-development/hovi-backend/database:latest
    image: registry.gitlab.com/hovi-team-development/hovi-backend/database:latest
    container_name: hovi-database-test
    ports:
      - 3308:3306
    networks:
      - back-tier-test
    env_file:
      - ../hovi-server/config/env-files/.env.gitlabCI
networks:
  back-tier-test:
